services:
  mongodb:
      image: mongo:6.0
      container_name: nexon-msa-mongodb
      ports:
        - '${MONGODB_PORT}:${MONGODB_PORT}'
      volumes:
        - mongodb_data:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER_NAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_USER_PASSWORD}
        - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
      networks:
        -  nexon-msa-network

  auth-service:
    build:
      context: services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      AUTH_SERVER_PORT: ${AUTH_SERVER_PORT}
      MONGODB_URI: mongodb://${MONGODB_USER_NAME}:${MONGODB_USER_PASSWORD}@mongodb:${MONGODB_PORT}/${MONGODB_DB_NAME}?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      LOG_LEVEL: debug
    networks:
      - nexon-msa-network

  api-gateway-service:
    build:
      context: services/event-api-gateway-service
      dockerfile: Dockerfile
    container_name: event-api-gateway-service
    depends_on:
      - auth-service
    environment:
      NODE_ENV: ${NODE_ENV}
      API_GW_SERVER_PORT: ${API_GW_SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SERVICE_URL: http://auth-service:${AUTH_SERVER_PORT}
      LOG_LEVEL: debug
    ports:
      - '${PUBLIC_PORT}:${API_GW_SERVER_PORT}'
    networks:
      - nexon-msa-network

volumes:
  mongodb_data:

networks:
  nexon-msa-network:
